version: "3.7"

services:
  app:
    build:
      args:
        user: anderson
        uid: 1000
      context: ./docker/php
      dockerfile: Dockerfile
    image: multiplier
    container_name: multiplier-app
    working_dir: /var/www
    volumes:
      - ./back:/var/www
    networks:
      - travellist

  db:
    image: postgres:13.1
    container_name: multiplier-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - travellist

  nginx:
    image: nginx:1.17-alpine
    container_name: multiplier-nginx
    command: nginx -g "daemon off;"
    ports:
      - "9090:80"
    volumes:
      - ./back:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    networks:
      - travellist

networks:
  travellist:
    driver: bridge
